import{S,a as q,i}from"./assets/vendor-DWXSRYDZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&l(g)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const d=document.querySelector(".gallery"),y=document.querySelector(".loader"),m=document.querySelector(".load-more"),R=new S(".gallery a",{captionsData:"alt",captionDelay:250}),p=t=>{const e=t.map(r=>`<li class="gallery-item">
                  <a href="${r.largeImageURL}">
                    <img src="${r.webformatURL}" width='360' height='200' alt="${r.tags}">
                  </a>
                  
                  <ul>
                      <li><b>Likes</b> ${r.likes}</li>
                      <li><b>Views</b> ${r.views}</li>
                      <li><b>Comments</b> ${r.comments}</li>
                      <li><b>Downloads</b> ${r.downloads}</li>
                  </ul>
                  
                  
              </li>`).join("");d.insertAdjacentHTML("beforeend",e),R.refresh()},v=()=>{d.innerHTML=""},f=()=>{y.style.display="block"},b=()=>{y.style.display="none"},w=()=>{m.style.display="block"},a=()=>{m.style.display="none"},P="51088577-7b521529318281431558696f8",L=async(t,e,r)=>{try{return(await q.get("https://pixabay.com/api/",{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:r,page:e}})).data}catch(l){i.error({title:"Error",message:l.message,position:"topRight"})}},h=document.querySelector(".form"),$=document.querySelector(".load-more");document.querySelector(".loader");document.querySelector(".gallery");let n,c;const u=40;h.addEventListener("submit",async t=>{if(t.preventDefault(),n=1,v(),c=t.target.elements.search.value.trim(),c===""){i.error({title:"Error",message:"Please enter a search term",position:"topRight"}),a();return}a(),f();try{const e=await L(c,n,u);if(e.hits.length===0){i.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a();return}p(e.hits),e.totalHits>e.hits.length&&w();const r=Math.ceil(e.totalHits/u);if(n>=r){i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results",position:"topRight"}),a();return}}catch(e){i.error({title:"Error",message:e.message,position:"topRight"})}finally{b()}h.reset()});$.addEventListener("click",async()=>{n+=1,f();try{const t=await L(c,n,u);if(t.hits.length===0){i.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a();return}a(),p(t.hits),t.totalHits>t.hits.length&&w();const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,behavior:"smooth"});const r=Math.ceil(t.totalHits/u);if(n>=r){i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results",position:"topRight"}),a();return}}catch(t){i.error({title:"Error",message:t.message,position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
