import{S as L,a as S,i}from"./assets/vendor-DWXSRYDZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250}),y=o=>{const e=o.map(t=>`<li class="gallery-item">
                  <a href="${t.largeImageURL}">
                    <img src="${t.webformatURL}" width='360' height='200' alt="${t.tags}">
                  </a>
                  
                  <ul>
                      <li><b>Likes</b> ${t.likes}</li>
                      <li><b>Views</b> ${t.views}</li>
                      <li><b>Comments</b> ${t.comments}</li>
                      <li><b>Downloads</b> ${t.downloads}</li>
                  </ul>
                  
                  
              </li>`).join("");h.insertAdjacentHTML("beforeend",e),q.refresh()},v=()=>{h.innerHTML=""},f=()=>{m.style.display="block"},b=()=>{m.style.display="none"},R=()=>{p.style.display="block"},l=()=>{p.style.display="none"},P="51088577-7b521529318281431558696f8",w=async(o,e,t)=>{try{return(await S.get("https://pixabay.com/api/",{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:t,page:e}})).data}catch(n){i.error({title:"Error",message:n.message,position:"topRight"})}},g=document.querySelector(".form"),$=document.querySelector(".load-more");document.querySelector(".loader");document.querySelector(".gallery");let a,c;const u=40;g.addEventListener("submit",async o=>{if(o.preventDefault(),a=1,v(),c=o.target.elements.search.value.trim(),c===""){i.error({title:"Error",message:"Please enter a search term",position:"topRight"}),l();return}l(),f();try{const e=await w(c,a,u);if(e.hits.length===0){i.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}y(e.hits),e.totalHits>e.hits.length&&R();const t=Math.ceil(e.totalHits/u);if(a>=t){i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results",position:"topRight"}),l();return}}catch(e){i.error({title:"Error",message:e.message,position:"topRight"})}finally{b()}g.reset()});$.addEventListener("click",async()=>{a+=1,f();try{const o=await w(c,a,u);y(o.hits);const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,behavior:"smooth"});const t=Math.ceil(o.totalHits/u);if(a>=t){i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results",position:"topRight"}),l();return}}catch(o){i.error({title:"Error",message:o.message,position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
