import{S as q,a as R,i}from"./assets/vendor-DWXSRYDZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),v=new q(".gallery a",{captionsData:"alt",captionDelay:250}),p=r=>{const e=r.map(o=>`<li class="gallery-item">
                  <a href="${o.largeImageURL}">
                    <img src="${o.webformatURL}" width='360' height='200' alt="${o.tags}">
                  </a>
                  
                  <ul>
                      <li><b>Likes</b> ${o.likes}</li>
                      <li><b>Views</b> ${o.views}</li>
                      <li><b>Comments</b> ${o.comments}</li>
                      <li><b>Downloads</b> ${o.downloads}</li>
                  </ul>
                  
                  
              </li>`).join("");m.insertAdjacentHTML("beforeend",e),v.refresh()},$=()=>{m.innerHTML=""},f=()=>{y.style.display="block"},b=()=>{y.style.display="none"},L=()=>{h.style.display="block"},n=()=>{h.style.display="none"},E="51088577-7b521529318281431558696f8",w=async(r,e,o)=>{try{return(await R.get("https://pixabay.com/api/",{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:o,page:e}})).data}catch(a){i.error({title:"Error",message:a.message,position:"topRight"})}},g=document.querySelector(".form"),P=document.querySelector(".load-more");document.querySelector(".loader");document.querySelector(".gallery");let c=1,l="";const S=40;let d=0;g.addEventListener("submit",async r=>{if(r.preventDefault(),c=1,$(),l=r.target.elements.search.value.trim(),l===""){i.error({title:"Error",message:"Please enter a search term",position:"topRight"}),n();return}n(),f();try{const e=await w(l,c,S);if(d=e.totalHits,e.hits.length===0){i.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n();return}p(e.hits),d>e.hits.length&&L()}catch(e){i.error({title:"Error",message:e.message,position:"topRight"})}finally{b(),g.reset()}});P.addEventListener("click",async()=>{c+=1,n(),f();try{const r=await w(l,c,S);if(r.hits.length===0){i.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n();return}p(r.hits);const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=d?(hideLoadMoreButton(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch(r){i.error({title:"Error",message:r.message,position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
